version: "3"

services:
  mininet:
    image: opennetworking/mn-stratum
    hostname: mininet
    container_name: mininet
    privileged: true
    tty: true
    stdin_open: true
    volumes:
      - ./tmp:/tmp
      - ./mininet:/mininet
    ports:
      - "50001:50001"
      - "50002:50002"
      - "50003:50003"
      - "50004:50004"
    entrypoint: "/mininet/topo.py"
  onos:
    image: onosproject/onos:2.2.1
    hostname: onos
    container_name: onos
    ports:
      - "8181:8181" # HTTP
      - "8101:8101" # SSH (CLI)
    volumes:
      - ./tmp/onos:/root/onos/apache-karaf-4.2.6/data/tmp
    environment:
      - ONOS_APPS=gui2,drivers.bmv2,lldpprovider,hostprovider
    links:
      - mininet
